name: delivery_autonoma
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.3.13
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5
  iconsax: ^0.0.8
  icons_flutter: ^0.0.4
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0
  image_picker: ^1.1.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.0
  get_storage: ^2.1.1
  path: ^1.9.0
  firebase_storage: ^11.7.3
  sn_progress_dialog: ^1.1.4
  flutter_masked_text2: ^0.9.1
  modal_bottom_sheet: ^3.0.0
  flutter_image_slideshow: ^0.1.6
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

   # Utility packages
 

flutter:

  uses-material-design: true

  assets:
   - assets/img/
   - assets/social/
   - assets/json/
   - assets/fonts/



  fonts:
     - family: SFProDisplay
       fonts:
         - asset: assets\fonts\SFProText-Bold.ttf
           weight: 700
